import { DataSource } from 'typeorm';
import { Empleado, Departamento, Estado } from 'src/empleados/entities/empleado.entity';

export async function seedEmpleados(dataSource: DataSource) {
  const repo = dataSource.getRepository(Empleado);

  const empleados: Partial<Empleado>[] = [
    {
      no_empleado: 1001,
      nombre: 'Juan',
      apellido_paterno: 'Pérez',
      apellido_materno: 'García',
      fecha_nacimiento: new Date('1990-05-12'),
      fecha_ingreso: new Date('2020-01-15'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Aduanas',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1002,
      nombre: 'María',
      apellido_paterno: 'López',
      apellido_materno: 'Hernández',
      fecha_nacimiento: new Date('1985-09-20'),
      fecha_ingreso: new Date('2018-03-01'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1003,
      nombre: 'Carlos',
      apellido_paterno: 'Ramírez',
      apellido_materno: 'Santos',
      fecha_nacimiento: new Date('1992-11-02'),
      fecha_ingreso: new Date('2021-07-10'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Embarques',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1004,
      nombre: 'Ana',
      apellido_paterno: 'Martínez',
      apellido_materno: 'Flores',
      fecha_nacimiento: new Date('1993-03-18'),
      fecha_ingreso: new Date('2019-06-20'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Aduanas',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1005,
      nombre: 'Luis',
      apellido_paterno: 'Hernández',
      apellido_materno: 'Ruiz',
      fecha_nacimiento: new Date('1988-07-25'),
      fecha_ingreso: new Date('2017-02-14'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1006,
      nombre: 'Sofía',
      apellido_paterno: 'Gómez',
      apellido_materno: 'Delgado',
      fecha_nacimiento: new Date('1995-01-30'),
      fecha_ingreso: new Date('2022-04-01'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Embarques',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1007,
      nombre: 'Miguel',
      apellido_paterno: 'Torres',
      apellido_materno: 'Vega',
      fecha_nacimiento: new Date('1987-11-11'),
      fecha_ingreso: new Date('2015-09-05'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Embarques',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1008,
      nombre: 'Camila',
      apellido_paterno: 'Grijalva',
      apellido_materno: 'Jara',
      fecha_nacimiento: new Date('2006-07-18'),
      fecha_ingreso: new Date('2018-12-10'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Coordinador Stock',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1009,
      nombre: 'José',
      apellido_paterno: 'Fernández',
      apellido_materno: 'Ríos',
      fecha_nacimiento: new Date('1989-04-09'),
      fecha_ingreso: new Date('2016-08-22'),
      departamento: Departamento.SEGURIDAD,
      puesto: 'Guardia de Caseta',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1010,
      nombre: 'Patricia',
      apellido_paterno: 'Navarro',
      apellido_materno: 'Jiménez',
      fecha_nacimiento: new Date('1994-12-15'),
      fecha_ingreso: new Date('2020-05-03'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Customer Service',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1011,
      nombre: 'Fernando',
      apellido_paterno: 'Aguilar',
      apellido_materno: 'Salinas',
      fecha_nacimiento: new Date('1986-08-19'),
      fecha_ingreso: new Date('2014-11-07'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1012,
      nombre: 'Gabriela',
      apellido_paterno: 'Ortiz',
      apellido_materno: 'Ramírez',
      fecha_nacimiento: new Date('1997-02-28'),
      fecha_ingreso: new Date('2023-01-12'),
      departamento: Departamento.SEGURIDAD,
      puesto: 'Guardia de Caseta',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1013,
      nombre: 'Ricardo',
      apellido_paterno: 'Silva',
      apellido_materno: 'Martínez',
      fecha_nacimiento: new Date('1990-10-05'),
      fecha_ingreso: new Date('2019-09-01'),
      departamento: Departamento.SUPPLYCHAIN,
      puesto: 'Customer Service',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1014,
      nombre: 'Mónica',
      apellido_paterno: 'Reyes',
      apellido_materno: 'Cruz',
      fecha_nacimiento: new Date('1992-01-17'),
      fecha_ingreso: new Date('2021-03-25'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1015,
      nombre: 'Diego',
      apellido_paterno: 'Vázquez',
      apellido_materno: 'Moreno',
      fecha_nacimiento: new Date('1984-09-29'),
      fecha_ingreso: new Date('2012-07-18'),
      departamento: Departamento.SEGURIDAD,
      puesto: 'Guardia de Caseta',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1016,
      nombre: 'Mauricio',
      apellido_paterno: 'Chairez',
      apellido_materno: 'Moreno',
      fecha_nacimiento: new Date('1984-09-10'),
      fecha_ingreso: new Date('2023-07-15'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1017,
      nombre: 'Ernesto',
      apellido_paterno: 'De Alba',
      apellido_materno: 'Perez',
      fecha_nacimiento: new Date('1984-05-15'),
      fecha_ingreso: new Date('2022-04-21'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1018,
      nombre: 'Gamaliel',
      apellido_paterno: 'Govea',
      apellido_materno: 'Renteria',
      fecha_nacimiento: new Date('1987-09-17'),
      fecha_ingreso: new Date('2022-04-22'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1019,
      nombre: 'Guillermo',
      apellido_paterno: 'Ochoa',
      apellido_materno: 'Renteria',
      fecha_nacimiento: new Date('1987-09-19'),
      fecha_ingreso: new Date('2022-04-22'),
      departamento: Departamento.TRANSPORTES,
      puesto: 'Chofer',
      estado: Estado.DISPONIBLE,
    },
    {
      no_empleado: 1,
      nombre: 'POR ASIGNAR',
      apellido_paterno: 'POR ASIGNAR',
      apellido_materno: 'POR ASIGNAR',
      fecha_nacimiento: new Date('1900-01-01'),
      fecha_ingreso: new Date('1900-01-01'),
      departamento: Departamento.SEGURIDAD,
      puesto: 'POR ASIGNAR',
      estado: Estado.OCUPADO,
    }
  ];

  for (const empleado of empleados) {
    const exists = await repo.findOne({ where: { no_empleado: empleado.no_empleado } });
    if (!exists) {
      await repo.save(repo.create(empleado));
    }
  }
  console.log('empleados ok');
}
